### ISSUE TITLE
TM4J improvement - riportálás több test cycle-ba

### ISSUE THREAD

**Issue by ljszalai** [i-Cell-Mobilsoft-Open-Source/roaster#99]
Szükség lenne, hogy a tesztek csoportosan kimutathatóak legyenek riportolás szempontjából. 
A test case-ek alapján csoportokra lehetne bontani a futtatható teszteset halmazokat.
Az elképzelés a konfiguráció módosításával ilyen formán nézne ki: 
```
roaster:
  tm4j:
    environment: Local
    enabled: false
    projectKey: RDEV
    defaultTestCycleKey: RDEV-C11
    server/mp-rest/url: https://jira.myserver.com
    server/basicAuthToken: G00dDagi10ZXSp3CtruMG1ZhnFTIz
    cycle:
      login: RDEV-C12
      chart: RDEV-C25
      checkout: RDEV-117
```
Ezzel a `@Tag("login")` taggel megjelölt tesztek a C12 test cycle-be jelentenék az eredményüket, a `@Tag("chart")` tesztek a C25-be, ... ami pedig nincs így felsorova, az a `defaultTestCycleKey` által meghatározott C11-be. 
Kompatibilitási ok miatt meg lehetne hagyni a `defaultTestCycleKey` mellett a jelenlegi `testCycleKey`-t is.
